apiVersion: v1
kind: Service
metadata:
  name: collector-service
  labels:
    app: collector-service
spec:
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
  selector:
    app: collector-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-service
      version: v1
  template:
    metadata:
      labels:
        app: collector-service
        version: v1
    spec:
      containers:
      - image: pallavireddy/collector-service:public
        imagePullPolicy: IfNotPresent
        name: collector-service
        ports:
        - containerPort: 8080
