
# POST call
POST http://34.94.1.56:80/book
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: token=;

{
  "cinemaId": "1",
  "movieId": "1",
  "showTime": "13:00",
  "seats": "2",
  "cardNumber": "123467890123",
  "nameOnCard": "John",
  "expMonth": "1234",
  "cvv": "000",
  "cardType": "discover",
  "userId": "1",
  "email": "abc@abc.com"
}

###