##################################################################################################
# Movies Service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmpe295-movies-service
---
apiVersion: v1
kind: Service
metadata:
  name: cmpe295-movies-service
  labels:
    app: cmpe295-movies-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: cmpe295-movies-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmpe295-movies-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmpe295-movies-service
      version: v1
  template:
    metadata:
      labels:
        app: cmpe295-movies-service
          version: v1
        spec:
          serviceAccountName: cmpe295-movies-service
          containers:
            - image: gcr.io/engaged-oarlock-288121/node-app:v3
              imagePullPolicy: Always
              name: cmpe295-movies-service
              ports:
                - containerPort: 8080
              env:
                - name: PORT
                  value: "8080"
                - name: DB_USERNAME
                  value: ""
                - name: DB_PASSWORD
                  value: ""
                - name: DB_HOST
                  value: ""
                - name: DB_PORT
                  value: ""
                - name: DB_NAME
                  value: ""