##################################################################################################
# Payment Service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmpe295-payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: cmpe295-payment-service
  labels:
    app: cmpe295-payment-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: cmpe295-payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmpe295-payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmpe295-payment-service
      version: v1
  template:
    metadata:
      labels:
        app: cmpe295-payment-service
        version: v1
    spec:
      serviceAccountName: cmpe295-payment-service
      containers:
      - image: gcr.io/distribute-tracing/payment-service:v1
        imagePullPolicy: Always
        name: cmpe295-payment-service
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
