##################################################################################################
# service 1
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cmpe295-app-4
---
apiVersion: v1
kind: Service
metadata:
  name: cmpe295-app-4
  labels:
    app: cmpe295-app-4
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: cmpe295-app-4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmpe295-app-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmpe295-app-4
      version: v1
  template:
    metadata:
      labels:
        app: cmpe295-app-4
        version: v1
    spec:
      serviceAccountName: cmpe295-app-4
      containers:
      - image: swadasmaunil/tracing-sample-app:public
        imagePullPolicy: IfNotPresent
        name: cmpe295-app-4
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: service4
        - name: PORT
          value: "8080"
        - name: SERVICE_REQUEST_LIST
          value: "" 

