# GET call
GET http://34.94.67.193:80/cinema/1/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: TOKEN=asasd;

###

# POST call
POST http://localhost:8080/api
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: token=;

{
  "key": "value"
}

###

# PUT call
PUT http://localhost:8080/api
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: token=;

{
  "key": "value"
}

###

# DELETE call
DELETE http://localhost:8080/api?param1=1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###